name: MSBuild

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  SOLUTION_FILE_PATH: df.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        platform: ['Win32', 'x64']

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: recursive
          
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build ${{matrix.platform}}
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{matrix.platform}} ${{env.SOLUTION_FILE_PATH}}
